### ISSUE TITLE
ExpoSpeechRecognitionModule.stop method error

### ISSUE THREAD

**Issue by Navid-gh** [jamsch/expo-speech-recognition#14]
it looks like the stop method doesn't have any args so doing `onPress={ExpoSpeechRecognitionModule.stop}` will cause an error as it gets an event as an arg at least for the Hermes engine for Android.

> Error: Received 1 arguments, but 0 was expected, js engine: hermes

so I think it's better to use
`<Button title='Stop' onPress={() => ExpoSpeechRecognitionModule.stop()} />`

but as far as I know, this doesn't have to be an error, idk why I got this error on my physical device.

Please correct me if I'm wrong.

**Comment by jamsch** [comment]
Thank you for spotting that, @Navid-gh! The underlying issue is to do with how function binding works in JS (which we don't want to pass through to our native module). I've just updated the APIs to drop any bindings from the stop & abort functions.
