### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'speechRecognitionPermission')

### ISSUE THREAD

**Issue by alphaCoder** [jamsch/expo-speech-recognition#19]
Thanks for creating this package. I downloaded the source code and able to run the example. I installed the package on brand new expo app and tried to run `npm run ios`, I get the below error.  Same thing happens for an existing expo app.

Can you please suggest if I am missing anything?

![image](https://github.com/user-attachments/assets/dfaed5e3-db61-4fda-9651-97298f7b88d3)

**Comment by alphaCoder** [comment]
my bad, I am able to resolve this issue. I had misconfigured plugin in app.json. Thanks for sharing this library.

**Comment by elongstreet88** [comment]
What was the fix for this? I'm hitting this too and trying to figure out what i'm doing wrong:

VSCode highlights it: Plugin definition is empty, expected a file or dependency name(PLUGIN_DEFINITION_INVALID)

<img width="761" alt="image" src="https://github.com/user-attachments/assets/96291676-49c3-4696-8c9b-0f121f10b6f8">

**Comment by jamsch** [comment]
@elongstreet88 You need to wrap it in square brackets:

```json
 "plugins: [
    "expo-router",
    [
      "expo-speech-recognition",
      {
        "microphonePermission": "Allow $(PRODUCT_NAME) to use the microphone.",
        "speechRecognitionPermission": "Allow $(PRODUCT_NAME) to use speech recognition.",
        "androidSpeechServicePackages": ["com.google.android.googlequicksearchbox"]
      }
    ]
  ],
```

**Comment by elongstreet88** [comment]
AH, that took an embarrassing amount of time to notice.
It might be worth adding the "expo-router" to the README show this syntax for additional plugins, as i don't think its terribly intuitive.
Or maybe i'm just slow :).

Thanks!
