### ISSUE TITLE
More supported languages.

### ISSUE THREAD

**Issue by thebiltheory** [jamsch/expo-speech-recognition#25]
Are there any plans to add more supported languages?

<img width="1027" alt="Screenshot 2024-09-26 at 4 39 46 PM" src="https://github.com/user-attachments/assets/26754d78-8da2-4240-88e4-5011a0505e89">

**Comment by jamsch** [comment]
Hey @thebiltheory, thank you for the mention! I don't currently have any public socials, but I do hang out on the Expo Developers Discord with the handle "Trucidare".
