### ISSUE TITLE
Is is possible to re-bind event listeners on state changes?

### ISSUE THREAD

**Issue by danny188** [jamsch/expo-speech-recognition#34]
Hi, is it possible to change the event listener that is given to a speech recognition event (such as "end") when a state variable changes? I'm trying to do something like below, but I believe it breaks the rules of hooks:

```
  useEffect(() => {
    useSpeechRecognitionEvent("end", () => {
      if (recognizing) {  
        handleStart(); // restarts speech recognition
      }
    });
  }, [recognizing])
```

Basically, I'm trying to change how the "end" event listener behaves based on a state variable.

Thanks.

**Comment by jamsch** [comment]
Hey @danny188, you can substitute the `useSpeechRecognitionListener` with `addSpeechRecognitionListener` in this context. The latter returns a "remove' function so that you can clean it up in an effect.
