### ISSUE TITLE
Measure real time sound level

### ISSUE THREAD

**Issue by danny188** [jamsch/expo-speech-recognition#39]
Hi,

Does this library offer a way to detect the sound/volume level of speech in real time? My goal is to play a pulsing animation whenever someone starts talking.

Can another library such as [react-native-sound-level](https://www.npmjs.com/package/react-native-sound-level) be used together at the same time while expo-speech-recognition is recognizing speech?

Thanks.

**Comment by jamsch** [comment]
Hey @danny188 I'm currently working on that now in this PR: https://github.com/jamsch/expo-speech-recognition/pull/37

**Comment by danny188** [comment]
Wow what a coincidence! Thanks 😀

**Comment by jamsch** [comment]
Hey @danny188 I've released this feature for v0.2.24, here's the docs on how to enable it: https://github.com/jamsch/expo-speech-recognition?tab=readme-ov-file#volume-metering

**Comment by danny188** [comment]
Thanks @jamsch! Planning to make use of this feature next week.
