### ISSUE TITLE
Recording stops after 1 minute

### ISSUE THREAD

**Issue by ansh** [jamsch/expo-speech-recognition#42]
After 1 minute of recording, it automatically stops

**Comment by jamsch** [comment]
Hey @ansh, can you let me know more?

- The OS and version you're running -- continuous functionality varies quite a lot based on platform
- The options you're using with `ExpoSpeechRecognitionModule.start({...})`

**Comment by ansh** [comment]
Sorry, I saw that it is a limitation on iOS. Will close this issue. @jamsch

**Comment by jamsch** [comment]
@ansh No problem! At one point I'm sure I'll be able to implement a workaround for the limitation of the underlying `SFSpeechURLRecognitionRequest` API.

**Comment by ansh** [comment]
@jamsch How would you go about doing that? I'd love to give it a shot.

**Comment by jamsch** [comment]
@ansh Essentially we're using the `append(buffer)` function from an instance of `SFSpeechAudioBufferRecognitionRequest` for microphone input. We'd need to do something similar to load the audio file in to a PCM buffer and, at chunks, feed it in to to speech recognizer instance using that append function. Not sure how it'd work on how fast you can append it though.

**Comment by YourAverageTechBro** [comment]
@jamsch Is there any chance you have gotten around to adding a work around to the 1 minute limit yet? Currently working on an app that requires live transcription and would prefer to us the on device transcription instead of a cloud based provider if possible.

**Comment by jamsch** [comment]
Hey @YourAverageTechBro, haven't visited this since then, but I think I should be able to get this implemented in the next day or two. Just a note though: I won't be able to implement anything for Android 12 and below, so you'll still likely need to use remote transcription APIs. There is a `supportsRecording()` API that you could use to distinguish whether to also use file-based transcription.

**Comment by YourAverageTechBro** [comment]
@jamsch amazing! looking forward to it :)

**Comment by jamsch** [comment]
@YourAverageTechBro Just deployed v1.1.0 (for Expo SDK 52). I've tested it with 1/2 channel WAV and 1-channel MP3 audio which seem okay. Let me know if you have any issues! I've also exposed a `audioSource.chunkDelayMillis` option to control the speed at which the audio is streamed to the recognizer in the case you run in to any issues. 

As for permissions, I don't actually think you need to ask the user for any permissions on iOS if you're going to use on-device recognition, however on Android you still will need to.

**Comment by YourAverageTechBro** [comment]
@jamsch is there any way you could add Expo SDK 51 support? I'm having some trouble upgrading my app to 52.

**Comment by jamsch** [comment]
@YourAverageTechBro no problem! I've just cherry-picked the last few commits and published it under version 0.3.0 (under the npm tag `sdk-51`). I haven't thouroughly tested out these cherry picked commits as I needed to do some changes for SDK 51, but hopefully it should be okay!
