### ISSUE TITLE
Even though I set requiresOnDeviceRecognition to false, an error occurs as if OnDeviceRecognition is enabled.

### ISSUE THREAD

**Issue by NamHyeongKeol** [jamsch/expo-speech-recognition#57]
versions
```
expo-speech-recognition: ^0.2.24
android: 14
device: SM_A528N (samsung)
```

my code
```
await ExpoSpeechRecognitionModule.start({
  lang: sourceLang,
  interimResults: true,
  maxAlternatives: 1,
  requiresOnDeviceRecognition: false,
  continuous: true,
  contextualStrings: ['my app'],
});
```

app.json
```
"plugins": [
  "expo-router",
  "expo-speech-recognition"
],
```

error log
```
 LOG  EVENT: start - Speech recognition started
 LOG  EVENT: error {"code": "language-not-supported", "message": "Requested language is supported, but not yet downloaded."}
 LOG  EVENT: end - Speech recognition ended
```

additional log for getSupportedLocales, getSpeechRecognitionServices, getDefaultRecognitionService
```
 LOG  Supported locales: cmn-Hans-CN, cmn-Hant-TW, de-AT, de-BE, de-CH, de-DE, en-AU, en-CA, en-GB, en-IE, en-IN, en-SG, en-US, es-ES, es-US, fr-BE, fr-CA, fr-CH, fr-FR, hi-IN, id-ID, it-CH, it-IT, ja-JP, ko-KR, pl-PL, pt-BR, ru-RU, th-TH, tr-TR, vi-VN
 LOG  On-device locales: cmn-Hant-TW, en-US, ko-KR
 LOG  Speech recognition services: com.google.android.as, com.google.android.tts, com.samsung.android.bixby.agent
 LOG  Default recognition service: com.google.android.as
```

Now I can start ExpoSpeechRecognitionModule with only on-device locales (cmn-Hant-TW, en-US, ko-KR). For any other locales, I encounter the error log mentioned above. I want to use online speech recognition. Is there a way to solve this problem?

**Comment by jamsch** [comment]
@NamHyeongKeol It seems like on your device the default recognition service is `com.google.android.as`, which is meant to be only for on-device recognition. You'll need to specify `androidRecognitionServicePackage: "com.google.android.tts"` when calling the start() function.

**Comment by NamHyeongKeol** [comment]
> @NamHyeongKeol It seems like on your device the default recognition service is `com.google.android.as`, which is meant to be only for on-device recognition. You'll need to specify `androidRecognitionServicePackage: "com.google.android.tts"` when calling the start() function.

Thank you! I'm not sure why it worked fine with TTS before without that setting, but it's working well now after applying it, just like you said.

**Comment by jamsch** [comment]
> Thank you! I'm not sure why it worked fine with TTS before without that setting, but it's working well now after applying it, just like you said.

No problem! Just a note though: I don't think `com.google.android.tts` is installed on all Android devices. I'm pretty sure on Android 12 and below it uses `com.google.android.googlequicksearchbox` as the default recognition engine.

Regarding your default recognition engine: I think what may have happened is that you've configured it in the Settings app, or uninstalled/disabled `com.google.android.tts` and then reinstalled/re-enabled it (which may require a reboot of your device).
