### ISSUE TITLE
Compiling error on iOS - cannot infer return type for closure with multiple statements; add explicit type to disambiguate

### ISSUE THREAD

**Issue by quantmvo-kms** [jamsch/expo-speech-recognition#6]
I'm switching from `react-native-voice/voice` to your library. I've tried running on Android and found out that it worked well. However, on iOS, I ran `expo run:ios` and facing the following error while compiling. I'm very appreciate if you can take a look at this error. Thanks!

My project is using Expo SDK 51 and the latest version of your library from npm (0.2.11)

```shell
❌  (node_modules/@jamsch/expo-speech-recognition/ios/ExpoSpeechRecognitionModule.swift:208:54)

  206 |     }
  207 | 
> 208 |     Function("getAudioSessionCategoryAndOptionsIOS") {
      |                                                      ^ cannot infer return type for closure with multiple statements; add explicit type to disambiguate
  209 |       let instance = AVAudioSession.sharedInstance()
  210 | 
  211 |       let categoryOptions: AVAudioSession.CategoryOptions = instance.categoryOptions

› Compiling expo-file-system Pods/ExpoFileSystem » EXFileSystemLocalFileHandler.m
› Compiling expo-file-system Pods/ExpoFileSystem » EXFileSystemAssetLibraryHandler.m

› 1 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jamsch** [comment]
@quantmvo-kms Very strange, never came across that build issue and we're on SDK 51 as well building on EAS. Is your XCode up-to-date? Anyways, I've just pushed an update at https://github.com/jamsch/expo-speech-recognition/commit/bb12fdcd9b43b0a7436f071bbe69b891f669b21d to attempt to fix this issue for you. Let me know if it works!

**Comment by quantmvo-kms** [comment]
@jamsch Thank you very much for your quick response. I have upgraded the dependency to version 0.2.12 and seen it worked well.
Compared to react-native-voice, your library doesn't miss the last word while working on Android as mentioned in [this comment](https://github.com/react-native-voice/voice/issues/195#issuecomment-526218476). Did you use some technique to clear that bug?

**Comment by jamsch** [comment]
@quantmvo-kms A colleague of mine ran in to a very similar issue to you (recognition of single syllable letters and numbers), and after researching it I came across this issue tracker bug on Google: https://issuetracker.google.com/issues/280288200?pli=1

The takeaway is that:
- On Android, you should either be using the `"web_search"` language model (through `androidIntentOptions.EXTRA_LANGUAGE_MODEL`), or enable on-device recognition (as long as they have the language model installed, this library has APIs to check and install this if necessary).
- On iOS, you can set the `iosTaskHint` to "confirmation"

I've actually just documented this specifically on the readme here: https://github.com/jamsch/expo-speech-recognition?tab=readme-ov-file#improving-accuracy-of-single-word-prompts

**Comment by quantmvo-kms** [comment]
Great work @jamsch! I really appreciate your support. Hope this project would be more popular soon!

**Comment by quantmvo-kms** [comment]
Hi @jamsch! I realized that your library and the one of react-native-voice use the same `LANGUAGE_MODEL_FREE_FORM` by default. But I discovered that your library worked better than the other. I tested with the text `I have a headache`, this one recognized the full text but react-native-voice only recognized `I have a`.

Does your library use other version of dependencies or there are other reasons behind this higher accuracy? Thanks for your attention in advanced!

The attached image below is a code snippet captured from `VoiceModule.java` file of react-native-voice.

<img width="977" alt="Screenshot 2024-08-23 at 6 27 31 PM" src="https://github.com/user-attachments/assets/3af30fd8-b93a-4e21-a084-49a1ffc4e91e">

**Comment by jamsch** [comment]
@quantmvo-kms It might be possible that you used `Voice.onSpeechPartialResults` without `Voice.onSpeechResults`?. On this library, the `result` event captures both of these and distinguishes the results by the `isFinal` attribute.
<img width="839" alt="screenshot" src="https://github.com/user-attachments/assets/12fdd518-2da8-4ce7-97e9-5991ae5e0700">

**Comment by quantmvo-kms** [comment]
You saved my life, @jamsch. You put my attention to those two function of react-native-voice, and I realized that my handlers for them had a bug. Thank you very much again.
I also saw that the number of downloads of your library on npm has increased. Keep your great work!
