### ISSUE TITLE
Expo SDK 50 - EAS Build Error

### ISSUE THREAD

**Issue by AnomalousLLC** [jamsch/expo-speech-recognition#65]
Installed the compatible version with: `npm install expo-speech-recognition@sdk-50`

However, we're unable to resolve this development build error.

![image](https://github.com/user-attachments/assets/c5e111ac-e92a-4771-b265-e7fa8c1e2b8e)

**Comment by jamsch** [comment]
Hi @AnomalousLLC, thank you for spotting that! I've just pushed a fix for the SDK 50 build. You should be able to install it with the same command (`npm install expo-speech-recognition@sdk-50`) or pin it to version `0.0.26`.

**Comment by AnomalousLLC** [comment]
Appreciate it! Confirmed resolved with `0.0.26`
