### ISSUE TITLE
Android verison is too old to trigger offline model download

### ISSUE THREAD

**Issue by theprashant-one** [jamsch/expo-speech-recognition#8]
Hi, thank you for this awesome package!

my issue is that triggering model download failling (am on android 13)

sample code:
```ts
const data = ExpoSpeechRecognitionModule.getSpeechRecognitionServices()
      // ["com.google.android.as", "com.google.android.tts"]

const res = await ExpoSpeechRecognitionModule.getSupportedLocales({
        // Stil failling for - data[0], data[1]
        androidRecognitionServicePackage: "com.google.android.googlequicksearchbox", // also this
})

      /*
      {"installedLocales": ["en-US"], "locales": ["cmn-Hans-CN", "cmn-Hant-TW", "de-AT", "de-BE", "de-CH", "de-DE", "en-AU", "en-CA", "en-GB", "en-IE", "en-IN", "en-SG", "en-US", "es-ES", "es-US", "fr-BE", "fr-CA", "fr-CH", "fr-FR", "hi-IN", "id-ID", "it-CH", "it-IT", "ko-KR", "pl-PL", "pt-BR", "ru-RU", "th-TH", "tr-TR", "vi-VN"]}
      */

await ExpoSpeechRecognitionModule.androidTriggerOfflineModelDownload({
        locale: res.locales[6],
})
```

![WhatsApp Image 2024-08-22 at 20 39 28_c20de576](https://github.com/user-attachments/assets/8b80c9f2-bc81-42b7-9ff8-0803e5324f8e)

**Comment by jamsch** [comment]
Hey @theprashant-one, good spotting! I hadn't yet implemented `triggerModelDownload` for Android 13 as it wasn't possible to listen for the status of the download in the SDK. As one temporary measure, the promise for `androidTriggerOfflineModelDownload` will have to instantly resolve, however you won't be able to know when the user has downloaded the model or if it failed.

**Comment by theprashant-one** [comment]
hi @jamsch thanks for quick reponse.
I will try this solution and let you know.

**Comment by theprashant-one** [comment]
One interesting thing I found is that I've downloaded several language packages, as you can see below, but the installed locales remain 'en-US'. Any guidance here?

```ts
{"installedLocales": ["en-US"], "locales": ["cmn-Hans-CN", "cmn-Hant-TW", "de-AT", "de-BE", "de-CH", "de-DE", "en-AU", "en-CA", "en-GB", "en-IE", "en-IN", "en-SG", "en-US", "es-ES", "es-US", "fr-BE", "fr-CA", "fr-CH", "fr-FR", "hi-IN", "id-ID", "it-CH", "it-IT", "ko-KR", "pl-PL", "pt-BR", "ru-RU", "th-TH", "tr-TR", "vi-VN"]}
```

![WhatsApp Image 2024-08-23 at 18 01 59_b530aedb](https://github.com/user-attachments/assets/6fadc387-a468-45b7-8172-bc20ba2c63fb)

**Comment by jamsch** [comment]
A bunch of menus to go through, I also got a bit mixed up because there were two Google apps that had options to download offline voice models too.

https://github.com/user-attachments/assets/f24396dc-1e3c-4f69-b952-ded19fedb4f5

**Comment by theprashant-one** [comment]
@jamsch, I can now see the downloaded locale. Thanks again!

**Comment by jamsch** [comment]
Sweet, closing this issue
