### ISSUE TITLE
Expo AV recording doesn't transcribe and giving "no-speech detected" error

### ISSUE THREAD

**Issue by theprashant-one** [jamsch/expo-speech-recognition#9]
Using the URI from recordingOptions output is working as expected, but it doesn't work when it comes to Expo AV recording. I have tried a few different outputFormat and audioEncoder settings, but with no luck.

```ts
const { recording } = await Audio.Recording.createAsync({
        isMeteringEnabled: true,
        android: {
          ...Audio.RecordingOptionsPresets.HIGH_QUALITY.android,
          extension: ".wav",
          outputFormat: AndroidOutputFormat.DEFAULT,
          audioEncoder: AndroidAudioEncoder.DEFAULT,
          numberOfChannels: 1,
          sampleRate: 16000,
        },
        ios: {
          ...Audio.RecordingOptionsPresets.HIGH_QUALITY.ios,
          extension: ".wav",
          outputFormat: IOSOutputFormat.LINEARPCM,
        },
        web: {
          mimeType: "audio/wav",
          bitsPerSecond: 128000,
        },
      })


ExpoSpeechRecognitionModule.start({
        lang: "en-US",
        interimResults: true,
        audioSource: {
          /** Local file URI */
          uri: recording.getURI(),
          /** [Android only] The number of channels in the source audio. */
          audioChannels: 1,
          /** [Android only] A value from AudioFormat - https://developer.android.com/reference/android/media/AudioFormat */
          audioEncoding: AudioEncodingAndroid.ENCODING_PCM_16BIT,
          /** [Android only] Audio sampling rate in Hz. */
          sampleRate: 16000,
        },
      })
```

**Comment by jamsch** [comment]
Hey @theprashant-one, I haven't tried expo-av yet to record audio but for what it's worth I've got a sample audio file with the config here: https://github.com/jamsch/expo-speech-recognition/tree/main/example/assets/audio and the usage:

https://github.com/jamsch/expo-speech-recognition/blob/bb12fdcd9b43b0a7436f071bbe69b891f669b21d/example/App.tsx#L792-L815

Android in particular is very picky with audio formats and only really works with 16-bit PCM WAV audio. Alternatively, you can also use this library to record audio instead (add `recordingOptions.persist: true` when starting). I'll try though to reproduce this issue and see if there's anything I can do on my end.

**Comment by jamsch** [comment]
After a bit more investigation:

- On Android, there's an undocumented limit on the file size of the audio source in the stream packet (around 200kb). I'll have to decode the audio source in to 16-bit PCM audio and downsample it in to a stream.
- On iOS, using `SFSpeechURLRecognitionRequest` has a hard limit of 1 minute of recognition for a given file so I may consider exploring using the default buffer request + reading the audio in to that buffer.

For the time being, you'll have the best luck using `recordingOptions.persist` until I figure out a better solution specifically for Android. It would be nice though being able to pass in long form audio for on-device transcription.

**Comment by theprashant-one** [comment]
Thanks for the detailed update! 

I'll stick with recordingOptions.persist for now and look forward to any further solutions, especially for handling longer audio on Android.

**Comment by jamsch** [comment]
I've just published an update on `v0.2.14` that provides long form audio file transcription for Android, the following formats are what I've tested:

- 16000hz 16-bit 1-channel PCM WAV
- 16000hz MP3 1-channel
- 16000hz MP3 2-channel
- 16000hz ogg vorbis 1-channel

You can use the following settings on `expo-av` which seems to work:

https://github.com/jamsch/expo-speech-recognition/blob/1c70b66942021560c0b655505a7c4daeff5b3598/example/App.tsx#L1055-L1064

And the audio source settings:

https://github.com/jamsch/expo-speech-recognition/blob/1c70b66942021560c0b655505a7c4daeff5b3598/example/App.tsx#L1124-L1128

**Comment by theprashant-one** [comment]
Hey @jamsch, I tested the format you mentioned, and it's working. Although the transcription quality isn't quite up to the mark, the process is functioning correctly. You can close this issue now. Thank you so much!

**Comment by jamsch** [comment]
Hey @theprashant-one, you may just want to play around with increasing the `chunkDelayMillis` setting on the `audioSource` option in case the transcription is missing words or phrases. By default it's around 50ms for remote speech recognition and 15ms for ondevice.
